name: Compile the student ZIP file

on: [push, pull_request]

jobs:
  compile-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      
      - name: Create temporary output folder
        run: "rm -Rf ./output; mkdir ./output"

      - name: Install markdown-to-pdf
        run: "npm install --prefix . md-to-pdf"
      
      - name: Compile PDF exam
        run: "node node_modules/md-to-pdf/dist/cli.js --body-class 'markdown-body' --css '.page-break { page-break-after: always; } .markdown-body { font-size: 10px; } .markdown-body pre > code { white-space: pre-wrap; }' --stylesheet 'https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/2.10.0/github-markdown.min.css' ./src/PE1.md"
      
      - name: Create student folder
        run: "python ./pkg/make-student-zip.py output/ZoomRooms src ZoomRooms.java"
      
      - name: Copy exam to folder
        run: "mv -v ./src/PE1.pdf ./output/ZoomRooms/exam.pdf"
      
      - run: "rsync --archive --quiet --exclude 'runConfigurations' --exclude '*.save' --exclude '.name' './pkg/template/.idea/' './output/ZoomRooms/.idea/'"
      - run: "rsync --archive --quiet './pkg/template/.lift/' './output/ZoomRooms/.lift/'"
      - run: "cp -vpr ./pkg/template/*.iml ./output/ZoomRooms/"
      
      - name: ZIP folder
        run: "rm -vRf ./PE1.zip; pushd ./output; ls -alht ZoomRooms; tree -a ZoomRooms; zip -vr PE1.zip ./ZoomRooms; popd; mv -v output/PE1.zip ./"
      
      - name: Version ZIP file
        run: "mv PE1.zip $(date +'PE1-%Y_%m_%d-%H_%M.zip')"
      
      # - name: Commit compiled PDF
      #   uses: EndBug/add-and-commit@v4
      #   with:
      #     message: "Commit compiled ZIP"
      #     add: "PE1.zip"
      #     cwd: "."
      #     force: true
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish release of compiled ZIP
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest release of the PE1 student ZIP"
          files: |
            PE1*.zip
